services:
  postgres-db:
    image: postgres:15-alpine
    container_name: contenedor_postgresql
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: service_desk
    ports:
      - "5432:5432"

  backend:
    image: service-desk-api:1.0.0
    container_name: service_desk_backend

    ports:
      - "8080:8080"

    depends_on:
      - postgres-db

    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}